site_name: simvue
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
  logo: images/logo.png
nav:
  - Home:
    - Welcome: index.md
    - Concepts: concepts.md
  - Introduction: introduction.md
  - Tracking & Monitoring:
    - Getting started: python-client/getting-started.md
    - Overview: python-client/overview.md
    - Configuration: python-client/configuration.md
    - Folders: python-client/folders.md
    - Metrics: python-client/metrics.md
    - Events: python-client/events.md
    - Artifacts: python-client/artifacts.md
    - Alerts: python-client/alerts.md
    - Logging handler: python-client/logging-handler.md
    - Obtaining data: python-client/obtaining-data.md
  - Analysis:
    - Retrieving runs: analysis/retrieving-runs.md
    - Metadata: analysis/metadata.md
    - Metrics: analysis/metrics.md
    - Events: analysis/events.md
  - Tutorial:
    - Introduction: tutorial/introduction.md
    - Tracking & Monitoring: tutorial/tracking-and-monitoring.md
    - Analysis: tutorial/analysis.md
    - Conclusion: tutorial/conclusion.md
  - Reference:
    - The Run class: reference/run.md
    - The Client class: reference/client.md
  - Examples:
    - Tensorflow: examples/basic-tensorflow.md
    - OpenFOAM: examples/openfoam.md
    - MOOSE: examples/moose.md
  - FAQ:
    - General: faq/general.md
repo_url: https://github.com/simvue-io
edit_uri: ""
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
