site_name: simvue
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: default
  logo: images/logo.png
  favicon: images/favicon.png
nav:
  - Home:
    - Welcome: index.md
    - Concepts: home/concepts.md
    - Terminology: home/terminology.md
  - Introduction: introduction.md
  - Tracking & monitoring:
    - Getting started: tracking-monitoring/getting-started.md
    - Overview: tracking-monitoring/overview.md
    - Configuration: tracking-monitoring/configuration.md
    - Folders: tracking-monitoring/folders.md
    - Metrics: tracking-monitoring/metrics.md
    - Events: tracking-monitoring/events.md
    - Artifacts: tracking-monitoring/artifacts.md
    - Alerts: tracking-monitoring/alerts.md
    - Launching processes: tracking-monitoring/launching_processes.md
    - Logging handler: tracking-monitoring/logging-handler.md
  - Analysis:
    - Retrieving runs: analysis/retrieving-runs.md
    - Folders: analysis/folders.md
    - Metadata: analysis/metadata.md
    - Metrics: analysis/metrics.md
    - Events: analysis/events.md
    - Artifacts: analysis/artifacts.md
  - Integrations:
    - Custom Connector: integrations/generic.md
    - MOOSE Connector: integrations/moose.md
    - Openfoam Connector: integrations/openfoam.md
  - Tutorial 1 - Basic Functionality:
    - Introduction: tutorial_basic/introduction.md
    - Tracking & Monitoring: tutorial_basic/tracking-and-monitoring.md
    - Analysis: tutorial_basic/analysis.md
    - Conclusion: tutorial_basic/conclusion.md
  - Tutorial 2 - Advanced Functionality:
    - Introduction: tutorial_advanced/introduction.md
    - Defining The Problem: tutorial_advanced/defining-the-problem.md
    - Tracking The Console Log: tutorial_advanced/tracking-the-log.md
    - Tracking Results: tutorial_advanced/tracking-results.md
    - Conclusion: tutorial_advanced/conclusion.md
  - Reference:
    - The Run class: reference/run.md
    - The Client class: reference/client.md
  - Examples:
    - Tensorflow: examples/basic-tensorflow.md
    - OpenFOAM: examples/openfoam.md
    - MOOSE: examples/moose.md
  - FAQ:
    - General: faq/general.md
repo_url: https://github.com/simvue-io
edit_uri: ""
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
