site_name: simvue
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
  logo: images/logo.png
  favicon: images/favicon.png
nav:
  - Home:
    - Welcome: home/index.md
    - Concepts: home/concepts.md
    - Terminology: home/terminology.md
  - Introduction: introduction.md
  - Tracking & monitoring:
    - Getting started: tracking-monitoring/getting-started.md
    - Overview: tracking-monitoring/overview.md
    - Configuration: tracking-monitoring/configuration.md
    - Folders: tracking-monitoring/folders.md
    - Metrics: tracking-monitoring/metrics.md
    - Events: tracking-monitoring/events.md
    - Artifacts: tracking-monitoring/artifacts.md
    - Alerts: tracking-monitoring/alerts.md
    - Logging handler: tracking-monitoring/logging-handler.md
    - Obtaining data: tracking-monitoring/obtaining-data.md
  - Analysis:
    - Retrieving runs: analysis/retrieving-runs.md
    - Metadata: analysis/metadata.md
    - Metrics: analysis/metrics.md
    - Events: analysis/events.md
  - Tutorial:
    - Introduction: tutorial/introduction.md
    - Tracking & Monitoring: tutorial/tracking-and-monitoring.md
    - Analysis: tutorial/analysis.md
    - Conclusion: tutorial/conclusion.md
  - Reference:
    - The Run class: reference/run.md
    - The Client class: reference/client.md
  - Examples:
    - Tensorflow: examples/basic-tensorflow.md
    - OpenFOAM: examples/openfoam.md
  - FAQ:
    - General: faq/general.md
repo_url: https://github.com/simvue-io
edit_uri: ""
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
