site_name: Simvue
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home:
    - Welcome: index.md
    - Concepts: concepts.md
  - Tracking simulations:
    - Getting started: python-client/getting-started.md
    - Overview: python-client/overview.md
    - Configuration: python-client/configuration.md
    - Folders: python-client/folders.md
    - Metrics: python-client/metrics.md
    - Events: python-client/events.md
    - Artifacts: python-client/artifacts.md
    - Alerts: python-client/alerts.md
    - Logging handler: python-client/logging-handler.md
    - Obtaining data: python-client/obtaining-data.md
  - Examples:
    - Basic Tensorflow: examples/basic-tensorflow.md
  - FAQ:
    - General: faq/general.md
repo_url: https://github.com/simvue-io
edit_uri: ""
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
