name: Deploy Website
on: [push, workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: pip install git+https://github.com/simvue-io/client.git@v1.0-rc
      - name: Create Reference Pages
        run: python scripts/create_api_docs.py docs/
      - run: mkdocs build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'
      - id: deployment
        uses: actions/deploy-pages@v1
